name: Sync to Docker Hub

on:
  push:
    branches: [ "main" ]
    paths:
      - 'README.md'
      - 'Dockerfile'
  release:
    types: [published]

jobs:
  sync-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: 0uwl/vaultkeeper
          readme-filepath: ./README.md
